# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-23 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
